# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.srcs/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/design_1_HDMI_Para_Cut_0_0.xci
# IP: The module: 'design_1_HDMI_Para_Cut_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/HDMI_ILA.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_ILA || ORIG_REF_NAME==HDMI_ILA} -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_ILA || ORIG_REF_NAME==HDMI_ILA} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/HDMI_ILA_ooc.xdc

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.srcs/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/design_1_HDMI_Para_Cut_0_0.xci
# IP: The module: 'design_1_HDMI_Para_Cut_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/HDMI_ILA.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_ILA || ORIG_REF_NAME==HDMI_ILA} -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_ILA || ORIG_REF_NAME==HDMI_ILA} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/design_1_HDMI_Para_Cut_0_0/src/HDMI_ILA/HDMI_ILA_ooc.xdc
