set_property SRC_FILE_INFO {cfile:D:/three_verilog/Eth_lwip/HW/Lwip_server_hw/Lwip_server_hw.srcs/constrs_1/new/Constant_eth.xdc rfile:../../../Lwip_server_hw.srcs/constrs_1/new/Constant_eth.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports HDMI_OUT_EN]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports HDMI_CLK_P]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports HDMI_TX_P[0]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports HDMI_TX_P[1]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports HDMI_TX_P[2]]
