# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.srcs/sources_1/bd/design_1/ip/design_1_DMA_Loop_AcpWr_0_0/design_1_DMA_Loop_AcpWr_0_0.xci
# IP: The module: 'design_1_DMA_Loop_AcpWr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] -quiet

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.srcs/sources_1/bd/design_1/ip/design_1_DMA_Loop_AcpWr_0_0/design_1_DMA_Loop_AcpWr_0_0.xci
# IP: The module: 'design_1_DMA_Loop_AcpWr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] -quiet

# IP: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/as_rdata_w64x2048_r16x8192/as_rdata_w64x2048_r16x8192_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==as_rdata_w64x2048_r16x8192 || ORIG_REF_NAME==as_rdata_w64x2048_r16x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/three_verilog/Eth_lwip_Acp/Eth_lwip_Acp/Eth_lwip_Acp.gen/sources_1/bd/design_1/ip/src/wdata_w64x1024_r64x1024/wdata_w64x1024_r64x1024_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wdata_w64x1024_r64x1024 || ORIG_REF_NAME==wdata_w64x1024_r64x1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
